name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build-and-deploy-to-gh-pages:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: build
        run: |
          npm install
          npm run-script build
          
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.2.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
